### PR TITLE
change the management of processor for load and dump in fields, becau…

### PR DESCRIPTION
**Pull request by bjamet**
…se of list that was not calling pre_load, post_load

The list.load() was calling directly field.load() without calls to pre_load ans post_load. The other fild, like PolymorphicList goes througt the mapper, so the pre_load and post_load were called. 

I propose to call pre_load and post_load in the load() method, and move the previous load() as a method to override in the other class inheriting field, since calling load() without pre_load and post_load is not used.

### CODE REVIEW

**Comment by bjamet** [comment]
Yes I could do that, But it's seams to me pre_load and post_load were not meant to be call outside the fields object, like _pre_dump and _post_dump that are private method.
 
pre_load and post_load where only called in the Schema object, so it seams the true behavior of  load() for object outside of fields is to manage pre_load and post_load. And so no need to repeat in `Schema` and in `List` calls to pre_laod and post_load

**Comment by bjamet** [comment]
Sorry, I didn't understand well the comment
I didn't thing of this solution

**Comment by bjamet** [comment]
Does pre_load and post load should have an impact on the element inside the list ??? 

you propose to define pre_load to call pre_load on each element of the list, 
and the same on post_load .... 
so there is a 'default' pre_load and post_load processor for list field ... what if the user add another pre_load processor (to reduce the list for example), does it be call before of after the 'default' one ?

**Comment by holinnn** [comment]
`Does pre_load and post load should have an impact on the element inside the list ???`
Yes because it's the purpose of the processor.

In fact for a list the default processor should be to call the inner field `pre_load` method for each element of the list in `value` and build a new list based on the return value.
If the user wants to redefine the processor he still can, it will be his responsibility to understand what he does and to call the field `pre_load` method.
I think this is the easiest solution.

**Comment by bjamet** [comment]
I didn't tink of this solution because I first look at PolymorphicList do understand how it was working for it. 
The fact that the mapper.load is called make that the pre_load and post_load are called together ..
So I tried to do it together also for the list .... 
But now I thinking about it, the pre_load and post_load of the element of polymorphic list themselves has no sences, since ther is no pre_load or post_load on schema directly ... but on the fields in the schema

**Comment by holinnn** [comment]
Yes `PolymorphicList` behaves differently because it uses `Schema` objects that will call `pre_load` etc. when they will be asked for loading data. So yes I don't think it's necessary to have this kind of feature on the `Polymorphic...` fields.

**Comment by bjamet** [comment]
following your recommendations : https://github.com/holinnn/lupin/pull/17

**Pull request closed without merging**
